Repository u413-284-si/ft_transcendence, pull requests merged in 2025-09, with the labels that each got.

#208 162 misleading toast
  app/frontend/src/AuthManager.ts
  app/frontend/src/routing/Router.ts
  app/frontend/src/services/serverSentEventsServices.ts
Labels: bug

#209 160 loading screen for dashboards
  app/frontend/src/charts/chartUtils.ts
  app/frontend/src/charts/tournamentsProgressOptions.ts
  app/frontend/src/charts/tournamentsSummaryOptions.ts
  app/frontend/src/locales/de.ts
  app/frontend/src/locales/en.ts
  app/frontend/src/locales/fr.ts
  app/frontend/src/locales/pi.ts
  app/frontend/src/locales/tr.ts
  app/frontend/src/views/StatsView.ts
  app/frontend/src/views/tabs/AbstractTab.ts
  app/frontend/src/views/tabs/FriendsTab.ts
  app/frontend/src/views/tabs/MatchesTab.ts
  app/frontend/src/views/tabs/TournamentsTab.ts
Labels: enhancement

#207 189 friendsview dont use router handleerror on smaller error
  app/frontend/src/locales/de.ts
  app/frontend/src/locales/en.ts
  app/frontend/src/locales/fr.ts
  app/frontend/src/locales/pi.ts
  app/frontend/src/locales/tr.ts
  app/frontend/src/views/FriendsView.ts
Labels: bug

#211 203 jwt can be swapped
  app/backend/src/controllers/auth.controllers.js
  app/backend/src/controllers/users.controllers.js
  app/backend/src/modules/auth.module.js
  app/backend/src/services/auth.services.js
  app/backend/src/services/events/sse.services.js
  app/backend/src/utils/error.js
  app/frontend/src/AuthManager.ts
  app/frontend/src/main.ts
  app/frontend/src/routing/Router.ts
  app/frontend/src/services/serverSentEventsServices.ts
  app/frontend/src/types/ServerSentEvents.ts
  app/frontend/src/views/AbstractView.ts
  app/frontend/src/views/ErrorView.ts
  app/frontend/src/views/FriendsView.ts
  app/frontend/src/views/GameView.ts
  app/frontend/src/views/HomeView.ts
  app/frontend/src/views/LoginView.ts
  app/frontend/src/views/MatchAnnouncementView.ts
  app/frontend/src/views/NewGameView.ts
  app/frontend/src/views/NewTournamentView.ts
  app/frontend/src/views/PlayerNicknamesView.ts
  app/frontend/src/views/ProfileView.ts
  app/frontend/src/views/RegisterView.ts
  app/frontend/src/views/ResultsView.ts
  app/frontend/src/views/SettingsView.ts
  app/frontend/src/views/StatsView.ts
  app/frontend/src/views/TwoFABackupCodeVerifyView.ts
  app/frontend/src/views/TwoFAVerifyView.ts
Labels: bug, enhancement

#212 134 set up hashicorp vault
  .env.example
  .gitignore
  Makefile
  app/Dockerfile
  app/backend/src/app.js
  app/backend/src/config/env.js
  app/backend/src/config/logger.js
  app/backend/src/controllers/auth.controllers.js
  app/backend/src/middleware/error.js
  docker-compose.yml
  package-lock.json
  package.json
  scripts/generate-ssl-certs.sh
  scripts/generate-vault-certs.sh
  scripts/vault-keys-backup.sh
  vault-agent/config/agent.hcl
  vault-agent/templates/cert.ctmpl
  vault-agent/templates/key.ctmpl
  vault/Dockerfile
  vault/config/vault.hcl
  vault/policies/app-policy.hcl
  vault/policies/healthcheck-policy.hcl
  vault/policies/nginx-policy.hcl
  vault/policies/setup-policy.hcl
  vault/tools/entry-point.sh
  vault/tools/healthcheck.sh
  vault/tools/setup-ssl-ca.sh
  waf/Dockerfile
  waf/modsecurity/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
  waf/nginx/tools/entry-point.sh
Labels: enhancement
